### ISSUE TITLE
Policeman break app update

### ISSUE THREAD

**Issue by Halibut80** [futpib/policeman#186] opened 2015-03-25 22:00 UTC
Policeman block requests to: <a href="https://download.cdn.mozilla.net/pub/mozilla.org/firefox/nightly/2015/03/2015-03-25-08-30-46-mozilla-central/firefox-39.0a1.en-US.win64.partial.20150325030206-20150325083046.mar">https://download.cdn.mozilla.net/pub/mozilla.org/firefox/nightly/2015/03/2015-03-25-08-30-46-mozilla-central/firefox-39.0a1.en-US.win64.partial.20150325030206-20150325083046.mar</a> and <a href="https://queue.taskcluster.net/v1/task/i-zXPtUuQ8G-EYooXAadfg/artifacts/public/build/firefox-39.0a1.en-US.win64.complete.mar">https://queue.taskcluster.net/v1/task/i-zXPtUuQ8G-EYooXAadfg/artifacts/public/build/firefox-39.0a1.en-US.win64.complete.mar</a> without any notification, when update manual, from menu "About Nightly".

Policeman 0.19pre1, Win 8.1 x64, Firefox Nightly 39.0a1 x64 BuildID:20150325030206

**Comment by futpib** [comment] 2015-07-04 10:07
Closed as duplicate of #212

**Closed by futpib** 2015-07-04 10:07 UTC
Labels: conflict
